# Configuración para GitHub Pages - Pop Pierce Studio
# Este archivo ayuda a GitHub Pages a entender cómo servir el sitio

# Configuración básica
baseurl: "/pop-pierce-studio-website"
url: "https://poppiercestudio.github.io"

# Configuración del sitio
title: "Pop Pierce Studio - Perforaciones Profesionales"
description: "Especialistas en perforaciones profesionales y seguras. Transforma tu estilo con nuestras perforaciones de calidad. Agenda tu cita por WhatsApp."
author: "Pop Pierce Studio"
email: "contacto@poppiercestudio.com"
lang: es
country: MX

# Configuración de GitHub Pages
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Configuración de build
markdown: kramdown
highlighter: rouge
theme: minima

# Configuración SEO
social:
  name: Pop Pierce Studio
  links:
    - https://www.facebook.com/share/14NFNhDsrFD/?mibextid=wwXIfr
    - https://wa.me/522351081694

# Configuración de tiempo
timezone: America/Mexico_City

# Configuración de colecciones
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title:output_ext

# Configuración de defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Configuración de exclude
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
