# Configuración para GitHub Pages
# Este archivo ayuda a GitHub Pages a entender cómo servir el sitio

# Configuración básica
baseurl: ""
url: "https://tu-usuario.github.io/pop-pierce-studio-website"

# Configuración del sitio
title: "Pop Pierce Studio"
description: "Perforaciones profesionales y seguras. Transforma tu estilo con nuestras perforaciones de calidad."
author: "Pop Pierce Studio"

# Configuración de GitHub Pages
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Configuración de build
markdown: kramdown
highlighter: rouge
theme: minima

# Configuración de colecciones
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title:output_ext

# Configuración de defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Configuración de exclude
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
